### ISSUE TITLE
Is the returned object a new object or the same object passed?

### ISSUE THREAD

**Issue by wmonecke** [jonschlinkert/set-value#20]
I am asking for the immutability to implement this with redux.
Thanks for the awesome work!!

**Comment by doowb** [comment]
The original "target" object is returned so you could work with that object in the same way as you would normally use an object in an "immutable" way with `redux`.

_Both examples below assume that `action` has a `.prop` property containing the object path of the value to set and a `.value` property with the value to set on the `state`._

**Before passing object to `set-value`**

```js
const reducer = (state = {}, action) => {
  return set({ ...state }, action.prop, action.value);
};
```

**After passing object to `set-value`**

```js
const reducer = (state = {}, action) => {
  return { ...set(state, action.prop, action.value) };
};
```

I hope this helps. I'm going to close this since it's a question, but feel free to continue the conversation if you'd like.

**Comment by wmonecke** [comment]
@doowb Thank you very very much!
