### ISSUE TITLE
Is this the expected result?

### ISSUE THREAD

**Issue by onokumus** [jonschlinkert/set-value#34]
```js
console.log(setValue({}, "{a..b}.c", "d"));
// => { '{a': { '': { 'b}': [Object] } } }
```

I don't think this should be the result.

**Comment by jonschlinkert** [comment]
That looks correct to me. If you don't want dots to be expanded they can be escaped. I'll keep an open mind though, what do you think the result should be?

**Comment by jonschlinkert** [comment]
@onokumus ping

**Comment by onokumus** [comment]
@jonschlinkert 

Like this example, I guess.
https://github.com/jonschlinkert/set-value/blob/master/examples.js#L37

**Comment by jonschlinkert** [comment]
Technically I think that result is correct. However, I get why you're interested in preserving `{..}`. This is why I added support for passing a custom `split` function. This is also an example of why I created [split-string](https://github.com/jonschlinkert/split-string). Since there is no easy way to handle strings like that without a real parser.

**Comment by onokumus** [comment]
Thanks @jonschlinkert
